version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.script
    ports:
      - 3000:3000
    environment:
      - APP_PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
